---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.weave.works
  resources:
  - automatedclusterdiscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.weave.works
  resources:
  - automatedclusterdiscoveries/finalizers
  verbs:
  - update
- apiGroups:
  - clusters.weave.works
  resources:
  - automatedclusterdiscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gitops.weave.works
  resources:
  - gitopsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
